### ISSUE TITLE
Streamng on "mixed" SSRC

### ISSUE THREAD

**Issue by gmemon** [jitsi/jitsi-videobridge#654] opened 2018-04-30 21:15 UTC
Hello All,

We are using jitsi-videobridge for 1:1 calls - i.e., video/audio traffic goes through the videobridge. We are also using jicofo for signaling. Our setup involves 1-way video and 2-way audio. As the traffic is going through the videobridge, the receiver of the video receives two video SSRCs - 1 is the actual video SSRC sent by the sender, and 2nd is the "mixed" SSRC sent by the videobridge.

So far so good.

For the most part we receive video on the original SSRC sent by video sender. But, at times, when the receiver sees a huge packet loss, we see traffic coming in on the mixed SSRC and the traffic on the actual SSRC drops to zero - i.e., it feels like traffic shifts from the actual SSRC to mixed SSRC. The visible impact of this shift is that the visible video freezes. After about a minute or so, the video traffic switches back to the actual SSRC and the video unfreezes.

My question is how can we avoid this behavior? Even in the face of huge packet loss, we still want to receive video traffic on the actual SSRC so that the video can recover as soon as packet loss is gone.

Another question is, is it possible to disable the mixed SSRC altogether?

Thanks,
-Ghulam

**Comment by sarumjanuch** [comment] 2018-04-30 23:33
We do experience exactly the same issue, even without huge packet drop...
https://github.com/jitsi/jitsi-videobridge/issues/598 see my comment here.

**Comment by sarumjanuch** [comment] 2018-05-01 17:29
Of course, it is not "mixed" but ssrc, which is announced by JVB during negotiation, the "bridge ssrc". From receiving party perspective, the switch happens between ssrc of caller and ssrc of the bridge.
You can see that very strictly clear on screenshot, that i have sent earlier:
![36906109-bb5fc3e0-1e3d-11e8-9ae3-f3cc7903c3a3](https://user-images.githubusercontent.com/4701803/39484238-c0441c84-4d7d-11e8-81e7-a877f6d555a7.png)
25431971 is ssrc of remote party and 2841039286 is bridge ssrc, take a look at bitReceivedPerSecond graph and compare them, you will understang what i am talking about.
I will build latest JVB asap, and will let you know, if that was the cause.

**Comment by jitsi-developers** [comment] 2018-05-01 19:32
Hi Eugene,

Here’s two key points

1. The bandwidth estimation drops when there’s packet loss.
2. The bridge will use the mixed ssrc to probe for bandwdith. If RTX is enabled, it will prefer to send actual media packets over the RTX stream.

Do you enable simulcast? How about RTX? Regardless, it is highly recommended to upgrade to the latest bridge.

Best,
George

**Comment by gmemon** [comment] 2018-05-01 20:15
Hi George,

Thanks for your response. The behavior that Eugene is seeing is exactly what we are seeing as well - i.e., packet loss causes the video SSRC to stop receiving traffic, and we see traffic on the "mixed" SSRC. According to your explanation the traffic that we see on the mixed SSRC is the bridge probing for bandwidth, right?

In our setup, we are not using simulcast. Rtx is enabled.

As per your suggestion, if we update the videobridge to the latest source code checked in, then we should stop seeing this behavior, right?

Eugene, we are you able to try out the new version of JVB? I will try it out later today.

Thanks,
-Ghulam

**Comment by sarumjanuch** [comment] 2018-05-01 21:44
Hi George,

First of all, thank a lot for your attention here guys! I am facing this issue for almost year, i already don't know where to look or what to try. 

I have the same scenario as topictarter:
RTX enabled
Simulcast not used

I have just tested latest JVB (1055), and now the video is broken completely. It is not working at all while downgrading to 1009 restore video functionality, but with issues mentioned above. 

The interesting stuff is that i see a lot of messages in 1055: 

```
JVB WARNING: [454] org.jitsi.videobridge.cc.BitrateController.log() Dropping an RTP packet, because the SSRC has not been signaled:3561370659

JVB WARNING: [454] org.jitsi.videobridge.cc.BitrateController.log() Dropping an RTP packet, because the SSRC has not been signaled:2857606205
JVB WARNING: [414] org.jitsi.impl.neomedia.rtp.remotebitrateestimator.RemoteBitrateEstimatorAbsSendTime.log() Probe failed, sent at 744186.0465116279 bps, received at 2000000.0 bps. Mean send delta: 10.75 ms, mean recv delta: 4.0 ms, num probes: 4
```

Despite that both ssrc's was signalled to bridge. See there is initial offer from caller and answer from callee: https://pastebin.com/iwN2Mv13. Take into accont that initial offer is initiator="false", i was always suspicious to this, since this is not the common scenario. If you need any information that i can provide, just let me know , and i will provide it asap .

**Comment by gpolitis** [comment] 2018-05-01 22:18
@sarumjanuch are you using a custom client or a custom signaling focus? The `Dropping an RTP packet` is a little misleading. If you're certain that the SSRC is signaled to the bridge, then it may also mean that a bandwidth distribution decision hasn't been taken. Bandwidth distribution decisions are taken in specific events but we've had reports in the past that this is somehow broken under certain scenarios.

**Comment by gmemon** [comment] 2018-05-01 22:24
I see the SSRC switching behavior in our custom client. So, I dont get the bandwidth or the connectivity error. I just see that the video freezes, and comes back after a minute or so.

**Comment by gpolitis** [comment] 2018-05-01 22:26
@gmemon can you post the jvb log somewhere?

**Comment by gmemon** [comment] 2018-05-01 22:54
part of the log is here:  https://pastebin.com/XbBUVkk4. I noticed that before I get the stream_hash warning, I get this warning: 

JVB 2018-05-01 21:22:16.504 WARNING: [11116] org.jitsi.videobridge.cc.BitrateController.log() Dropping an RTP packet, because the SSRC has not been signaled:1944969955

The log consists of these warnings entirely.

**Comment by sarumjanuch** [comment] 2018-05-01 23:26
@gpolitis yes, it is custom signaling focus.

**Comment by sarumjanuch** [comment] 2018-05-02 01:12
I made the full log of 1 to 1 call via the bridge on 1055 (broken condition). I may be messed up IP replacements to labels, but I believe it does not important here.  
https://pastebin.com/XjnXcQAA

**Comment by sarumjanuch** [comment] 2018-05-02 16:25
Also, this seems to happen regardless RTX is enabled or not.

**Comment by gmemon** [comment] 2018-05-05 20:14
An additional update here: before I see the format_no_found log message (e.g., JVB 2018-05-05 19:20:30.550 WARNING: [313] org.jitsi.impl.neomedia.transform.RetransmissionRequesterImpl.log() format_not_found,stream_hash=667457729), I see the following:

JVB 2018-05-05 19:20:30.550 SEVERE: [308] net.sf.fmj.media.Log.error() No format has been registered for RTP payload type (number) 107!

107 corresponds to H264. 

Because of this [issue](https://github.com/jitsi/jicofo/issues/276), I have added the following line to Jicofo: 

addParameterExtension(h264, "profile-level-id", "42e01f;level-asymmetry-allowed=1;packetization-mode=1;),

And I can see it getting signaled from Jicofo.

I have updated my entire stack to the latest stable jitsi repo. In addition, the modification to jicofo is on stable/jitsi-meet_2988 tag.

Please help!!

**Comment by havid0707** [comment] 2018-05-15 06:40
@gpolitis 
![image](https://user-images.githubusercontent.com/9440277/40040632-99751aec-584d-11e8-9e83-368249afd92d.png)
My Jvb version is 1055 but still have this problem, may I know 1055 include your fix or not?

**Comment by sarumjanuch** [comment] 2018-05-30 13:44
Hi Guys, is there any advice, that you can provide to try, or any place to look at, to try to eliminate this, except implementing simulcast? We have custom signalling focus, and also a custom client, and one does not simply put simulcast into the game. Otherwise, it seems that you should mention somewhere that simulcast is MTI on client\focus, for JVB to actually work, as this is not obvious at all.

**Comment by rhwu** [comment] 2018-05-31 20:18
Just like what gmemon mentioned previously, we are also seeing h264 issue with jvb 1055. The error log shows:
net.sf.fmj.media.Log.error() No format has been registered for RTP payload type (number) 107!

I did a bitset search and found it started from this commit:
https://github.com/jitsi/jitsi-videobridge/commit/9457cfa34

But I'm not sure yet which part of the libjitsi is causing the problem.

**Comment by rasos** [comment] 2018-06-11 11:00
Same issue here: tons of 
`org.jitsi.videobridge.cc.BitrateController.log() Dropping an RTP packet, because the SSRC has not been signaled:1340409189`

**Comment by gpolitis** [comment] 2018-06-11 19:38
@rhwu wrt "No format has been registered for RTP payload type (number) 107",  the RTX format needs a payload type and an associated payload type and the bridge needs to know about it.

@rasos @sarumjanuch make sure you properly signal all the SSRCs that you send to the bridge.

@gmemon you were probably observing stream corruption. There's a couple of recent fixes that prevent this, so I encourage you to use the latest bridge. You don't want to (and you can't) disable the bridge/mixed ssrc and you must make sure it's properly signaled across all your endpoints.

@sarumjanuch documentation is indeed lacking and it's complicated to get everything right, especially if you use your own signaling implementation, that's why we highly encourage people to use Jicofo whenever possible. If you can't do that for technical or whatever reasons, then we'll try our best to help you out but it will require time and effort to get it right.

Lastly, since JVB@1055 there's been a couple of important fixes so I encourage everybody to upgrade to that new version. 

I'm going to close this issue because it has become a big spaghetti soup with different problems from different people. It's much easier to answer to keep track of a single problem at a time, so please either open a new issue or use our mailing lists.

**Closed by gpolitis** 2018-06-11 19:38 UTC
