### ISSUE TITLE
Chrome 55.0.2860.0 canary doesn't connect

### ISSUE THREAD

**Issue by Stefan1oo** [jitsi/jitsi-videobridge#311] opened 2016-09-15 00:51 UTC
I never get the iceConnectionState = connected event when using Chrome dev channel 55.0.2860.0

WebRTC Internals show that Chrome is sending bytes to Jitsi but Jitsi never sends a byte back: bytesReceived	0

It works fine with Chrome 53.

Any idea?

**Comment by sarumjanuch** [comment] 2016-09-15 20:17
A quick glance, shows, that JVB has an issue with receiving DTLS from new chrome.  It keep it sending with no server hello, and on the server side there are errors in JVB log, i did wireshark trace, and compared Client Hello packets from 53 and 55. The only difference is in signature_algorithms. Attaching full log, of broken call, and print screen of DTLS client hello packets form both chromes.
![jvb dtls issue](https://cloud.githubusercontent.com/assets/4701803/18565891/4a3ca0b2-7b9a-11e6-944e-95f1f251d4cc.png)
[JVB_DTLS_broken.txt](https://github.com/jitsi/jitsi-videobridge/files/475496/JVB_DTLS_broken.txt)

**Comment by peili** [comment] 2016-09-15 20:54
Looks like Chrome 55 removed SHA-1.

**Comment by sarumjanuch** [comment] 2016-09-15 21:34
So far the roots are here https://github.com/bcgit/bc-java/blob/master/core/src/main/java/org/bouncycastle/crypto/tls/SignatureAndHashAlgorithm.java#L31. But this is far beyond, of my competition.

**Comment by jitsi-developers** [comment] 2016-09-15 22:36
We saw this too but notice meet.jit.si doesn't seem to suffer from it.  Our
libjitsi/jitsi-videobridge versions are a bit old at this point...is this
something that was fixed recently?

**Comment by sarumjanuch** [comment] 2016-09-15 22:54
Just dig for the reason why jitsi-meet is not suffering from this, and did find out that you mangle sdp answer  a=setup:active to a=setup:passive, this leads to JVB sends a client hello packet, not the client, and this issue happens when a client is active, so client sends DTLS client hello to JVB.

**Comment by sarumjanuch** [comment] 2016-09-15 23:08
This leads me to additional thoughts, that if your bridge is acting as setup:active then on focus level you should signal channel initiator to be false, as per this http://www.xmpp.org/extensions/inbox/colibri.html. Then, I wonder how did you not yet faced  https://github.com/jitsi/jitsi-videobridge/issues/279.

**Comment by Kenny-House** [comment] 2016-09-16 15:21
Wanted to add what appears to be a relevant WebRTC issue: https://bugs.chromium.org/p/webrtc/issues/detail?id=6342

The issue "Chrome 55 dev includes RFC violation in DTLS" notes Bouncy Castle incompatibility specifically.

**Comment by Kenny-House** [comment] 2016-09-21 21:06
Small update for those following this issue:

The Chromium team merged in some changes to BoringSSL to resolve this issue. Should land in Canary here shortly.

At root were changes in BoringSSL for TLS 1.3 that caused problems negotiating with BouncyCastle.

**Comment by Kenny-House** [comment] 2016-09-23 17:18
The Chromium updates have rolled out and I can confirm that things are working as expected again with Chrome 55.

I think this issue should be ok to close now @Stefan1oo ?

**Closed** 2016-09-23 17:58 UTC
