### ISSUE TITLE
Consider 2 or More Videobridge Instances With a Trunk Network Connection Between Them

### ISSUE THREAD

**Issue by clive1000** [jitsi/jitsi-videobridge#510] opened 2017-08-02 00:11 UTC
This is a suggested enhancement to the existing solution for consideration. It aims to cater for companies having multiple user sites and a single site where there is a mixture of internal and external conference users.

The use case being addressed is how to best to support  a mixture of on-site and off-site conference members and by extension, organisations with multiple sites.

Aims:
Increase scalability.
Reduce site internet download traffic
Improve image quality for local on-site users
Potentially improve network manageability

My suggestion is as follows:

Where a significant number of users are site based then some thought needs to be given to whether the Videobridge instance should be located internally or externally. My suggestion is that in some circumstances it may be helpful to have both: The external server serving the external users and the internal server serving the internal on-site users. 

In this case it would only be necessary to route to each server a single copy of each conference feed being managed by the other server(s). This would not affect uploads at the site/internet boundary but could reduce the downloads as only 1 copy is required rather than 1 copy per conference user. i.e. A kind of communications  trunk is created between the Videobridge instances that only communicates the needed data once, reducing the traffic at the site internet/internal network boundary..

From the point of view of network management this might be easier to set up and maintain the trunk connection. Also the network upload requirements of the site internet connection  should be reduced. Finally, the network traffic should be more consistent as it is not being constantly varied as the Videobridge software varies the video quality/bit rate, which should make the network load more predictable and hence manageable.

In some instances the limited remaining service capability of the multiple server solution after a server failure may prove to be useful. The trunk link between the Videobridge instances could be doubled up for increased resilience.

I hope this is useful. Apologies if it has already been considered. If this is the wrong forum please transfer as necessary.

Best regards

Clive

**Comment by bgrozev** [comment] 2017-08-03 20:53
Hi Clive,

You bring up an interesting situation, and this is (one of) the right place to have a discussion.

We are actually currently working on interconnecting multiple jitsi-videobridge instances in a single conference. Something like what you describe should be possible with the design that we are working on, although your use-case is not one that we specifically have in mind. 

However, for the problem that you describe I think there is a much simpler solution that can already be deployed. As long as the jitsi-videobridge instance that you are using has an address in the private network, it should already be selected by ICE and used by clients on that network (while clients outside of the network should only be able to connect on the public address). Unless I am missing something this should solve your problem without introducing any of the extra complexity of the interconnected bridges solution. 

Please let me know if I missed something and this is not applicable to your problem -- if that is the case we would like to make sure that our multi-bridge design will cover your case.

Regards,
Boris

**Comment by clive1000** [comment] 2017-08-08 18:18
Hi Boris

Many thanks for your response and interest.

I understand that ICE facilitates crossing a NAT boundary only. I am actually thinking about the problem of potentially saturating a company's internet connectivity, especially if it is an ADSL link. I thought that collating all the external connections to a well connected hosted server and setting up a new "Trunk" protocol connection to connect with the company's internal Videobridge server would be helpful. The trunk connection would just need to carry one copy of the video feed and only when needed by the other instance of Videobridge. Conferences wholly external or wholly internal would mean no traffic on the trunk connection at all. I can quite see how videconferencing from the desktop could take-off dramatically and it would be a shame if it was prevented from reaching its potential due to the limits of the infrastructure.

Two more use cases I thought of were:

1. Connecting together the Videobridge instances of 2 or more company's who wished to collaborate on a project (with appropriate safeguards)
2. Conferencing between two regions/countries that have poor/high latency network links. In this case it could be beneficial to set up a special low latency link and route just the inter-region/country traffic through it. Minimising this traffic reduces the cost of the link. (The intra-region traffic does not appear on the trunk connection). 

If it is thought that such an arrangement with "Trunk" connections between Videbridge instances is useful then another issue presents itself:

For 2 or 3 instances of Videobridge there is just one connection between each instance. However as the number of instances increases then the number of trunk connections increases quickly (order n squared I believe) This is the same problem Videbridge itself was designed to solve.

Therefore, to connect more than 3 Viideobridge instances can I suggest a Supervideobridge that only handles trunk connections but in an analogous way to how Videobridge handles conference connections. i.e. Each instances of Videobridge connects to the Supervideobridge uses the trunk protocol described above and obtains and delivers just the video feeds required. This should overcome the problem of connecting 4 or more Videbridge instances without requiring a plethora of trunk network links.

I hope this is useful.

Cheers

Clive

**Comment by clive1000** [comment] 2017-08-11 16:42
Sorry, closed by accident. Still learning Github.

Just one more thought. It strikes me that the suggested enhancements above are analogous to creating a Content Delivery Network (CDN), except that in this case the traffic is in both directions. The aim is to better manage and ensure the quality and reliability of the service, especially as we are working in real time.

Cheers

Clive

**Comment by bgrozev** [comment] 2017-08-14 19:48
Thanks for the feedback.

I see your point about using one internal and one external bridge. We'll have that use-case in mind -- I think the current architecture will allow for it (we just need to have a way to select the correct bridge for each client).

About the other two points:
1. I think this problem should be solved on a different level.
2. That's one of our main use-cases (although minimizing the traffic between the bridges isn't a priority)

**Comment by tkd4444** [comment] 2018-04-25 13:09
@bgrozev Any updates on having 2 or more videobridges serving the same conference ?

Thanks !

**Comment by bgrozev** [comment] 2018-04-25 17:39
We now have a first version merged in master that we are currently testing. There are some pieces still missing (e.g. a selection algorithm which makes sense). 

You can set it up by having two jitsi-videobridge instances connected to jicofo and adding these to the bridges' config:
```
org.jitsi.videobridge.octo.BIND_ADDRESS=0.0.0.0
org.jitsi.videobridge.octo.PUBLIC_ADDRESS=1.2.3.4
org.jitsi.videobridge.octo.BIND_PORT=4096
```

And this to jicofo to force it to always split conferences to multiple bridges:
```
org.jitsi.jicofo.BridgeSelector.BRIDGE_SELECTION_STRATEGY=SplitBridgeSelectionStrategy
```

**Comment by tkd4444** [comment] 2018-04-25 19:35
Yeah, but could be like:

1. Videobridge in Europe 
2. Videobridge in US
3. Videobridge in Asia

Then you would have a domain name which would use a geolocation routing.

Would this work ?
Does it make sense ?

**Comment by bgrozev** [comment] 2018-04-25 19:40
> Would this work ?
> Does it make sense ?

Yes, but we have something else in mind for our implementation.

**Comment by tkd4444** [comment] 2018-04-25 20:01
What ? :-)

In the current state, could be this implemented in this way, without a need of much tweaking ? Would it open a connection for a videobridge with a specified domain instead of a IP or the hostname of the machine ?

**Comment by bgrozev** [comment] 2018-04-25 20:08
> What ? :-)
> 
> In the current state, could be this implemented in this way, without a need of much tweaking ? Would it open a connection for a videobridge with a specified domain instead of a IP or the hostname of the machine ?

No, because the selection of a videobridge instance is done by jicofo. We are working on a way to solve this problem, but it is going to work in a different way.

**Comment by tkd4444** [comment] 2018-04-25 20:47
Hmm, alright.

**Comment by soq2000** [comment] 2018-05-09 09:14
Dear all,
Can I resume that the latest version supporting several video bridges ? The number of bridges can be greater than 2 can't it ? What is the stream circulating between the bridges ? They are one stream with mixed audio / video or several audio and video streams?
Does the jicofo solve the load balance of bridges, meaning that whenever there are too many conference served by one bridge, another bridge will be involved to take over the job.
Thank you for your clarification.

**Comment by imtharik** [comment] 2018-09-06 09:12
Hi,
How can i run 1 conference in 2 video bridges. For example, 1 user from Singapore and another user from Sydney. I have 2 video bridges (1 in singapore and another in sydney) connected with Meet Server in Sydney. So I want singapore user should come through singapore video bridge and sydney user from sydney video bridge but on same conference (Meet server in Sydney). 

How I make this possible?
Also it will be good if I get any tutorial which explains the above situation.


Thanks in advance

**Comment by webintoit** [comment] 2018-09-06 10:44
@imtharik, just in terms,   you should provide `region info` into each  user frontend configuration (see `deploymentConfig` on original JM  deployment), also you should provide region to each videobridge configuration.  After all you should link  bridges with `Octo relay` from @bgrozev.  After all you should implement `BridgeSelectionStrategy` on Jicofo  to enable region based selection with linked bridges.

**Comment by bgrozev** [comment] 2018-09-07 15:45
On meet.jit.si we use a system based on Route53 and a set of geo-located HAProxy instances to make clients aware of their own region. Unfortunately this is a required piece and is not easy to reproduce, which is why we haven't published more documentation yet. See here for a very quick and dirty way to get this working for testing: https://gist.github.com/bgrozev/92b096db14cc980d7b734e156a8e6170

**Comment by youyi218** [comment] 2024-07-22 12:58
Hi, do we have any updates on this issue ? Especially @soq2000's question, when a new JVB is created, can Jicofo distribute new user on an existing conference to the new JVB ?

**Comment by bgrozev** [comment] 2024-07-24 09:33
@youyi218 yes. When a new user joins an existing conference jicofo selects a bridge for it among all available bridges. The selection is based on load of the bridges, the region of the user, and whether the bridge is already used in this conference. See here for detail: https://github.com/jitsi/jicofo/blob/master/jicofo-selector/src/main/kotlin/org/jitsi/jicofo/bridge/RegionBasedBridgeSelectionStrategy.kt

I'm going to close this issue since the original idea is already implemented. But feel free to continue to comment, re-open, or open a new one if you have more questions.

**Closed by bgrozev** 2024-07-24 09:33 UTC
