### ISSUE TITLE
Last-N not working properly

### ISSUE THREAD

**Issue by pastissolo** [jitsi/jitsi-videobridge#223] opened 2016-04-19 15:04 UTC
We have successfully installed the  Jitsi enviroment,
Videobridge + Jicofo + JitsiMeet  and  quickly developed a sample application.

The whole thing seems to work, both JitsiMeet  and our SampleApp can create a video conference for any number of users;

The only issue we can't figure out is that the  'channelLastN'  attribute doesn't appear to work properly.

After setting up  'channelLastN:2'  in the config.js, every participant can at most see 2 remote videos,
but the list of the visible remote streams is never updated:
the lastNchanged message is never received (actually it is only fired when a user joins or leaves the conference)
regardless of the message 'new dominant speaker:' being received by the videobridge.

Videobridge seems to send messages for the new dominant speaker but for the lastN active users changes.

PS:
we also installed the latest nightly videobridge build 4/18/2016

Does anyone has the same issue or some advice ???

**Comment by jitsi-developers** [comment] 2016-04-19 15:18
Can't tell for sure, but it's possible this is caused by the issue
addressed here: https://github.com/jitsi/jitsi-videobridge/pull/204 (this
fixes a problem where a change in the last-n, but not in the list of total
participants, can result in no last-n changed message sent).

**Comment by pastissolo** [comment] 2016-04-26 09:21
Yes,
the issue was solved by changing 
  ``  if (equalAsSets(conferenceSpeechActivityEndpoints, `endpointIds))`

back to

 ``   if `(conferenceSpeechActivityEndpoints.equals(endpointIds))`

in src/main/java/org/jitsi/videobridge/LastNController.java
as suggested in  #198.

**Comment by bgrozev** [comment] 2016-04-26 13:49
Yes, we merged Brian's fix (#204), so this shouldn't happen on master anymore.

**Closed by bgrozev** 2016-04-26 13:49 UTC
